projectRootJava: 'c:/github/azure-libraries-for-java'
projectRootDotNet: 'c:/github/azure-libraries-for-net'
readmeFile: 'README.md'
releaseNoteFileTemplate: 'notes/prepare-for-{0}.md'

previousVersion: '1.39.0'
releaseVersion: '1.39.1'

# JAVA / DOT_NET
releaseType: JAVA
